### PR TITLE
The PATH should not be hard coded and the directory should be checked if it exists or not.

### PR DESCRIPTION
**Pull request by Manuel4131**
As title.

### CODE REVIEW

**Comment by Manuel4131** [comment]
Also, add a `requirement.txt` file. With 
```python
pip install -r requirement.txt
```
The required packages can be automatically installed. 
Also, I prefer to use virtual environment (python3.4-3.6) to separate the working environments.

**Comment by a0726h77** [comment]
please check out to latest code, maybe resolve the file conflict.

**Comment by Manuel4131** [comment]
Hi, I wish that different python projects could own their unique packages and libraries. Thus, I suggest to use `pip` command to install the required packages with just one instruction.
```bash
pip install -r requirement.txt
```

**Comment by Manuel4131** [comment]
Hi, Yen. I sent a new request. 
1. Fix a bug in the source
2. Check the target directory exist before creating it.

**Pull request merged**
